name = "Everest"
description = "A simple Hugo theme."
homepage = "https://github.com/backtraxe/hugo-theme-everest"

license = "MIT"
licenselink = "https://github.com/backtraxe/hugo-theme-everest/blob/master/LICENSE"

min_version = "0.65.0"

[author]
name = "Backtraxe"
homepage = "https://github.com/backtraxe"
