name = "Everest"
description = "A simple Hugo theme."
homepage = "https://github.com/backtraxe/hugo-theme-everest"
license = "MIT"
licenselink = "https://github.com/backtraxe/hugo-theme-everest/blob/master/LICENSE.md"
tags = [
  "accessible",
  "multilingual",
  "responsive",
  "blog",
  "search",
  "simple",
  "light",
  "dark",
  "mobile",
  "gallery",
  "technical",
  "fast",
  "presentation",
]
features = [
  "accessible",
  "multilingual",
  "responsive",
  "grid",
  "sass",
  "search",
  "subtheme",
  "gallery",
  "technical",
  "fast",
  "presentation",
]
min_version = "0.65.0"

[author]
name = "Backtraxe"
homepage = "https://github.com/backtraxe"
