baseURL = "http://example.org"
title = "Hugo Theme Everest Demo Site"
theme = "Everest"

languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
hasCJKLanguage = true

summaryLength = 70
buildFuture = true

copyright = "&copy;{year}, All Rights Reserved"
timeout = "300s"
enableEmoji = true
paginate = 13
rssLimit = 100

enableGitInfo = false
# googleAnalytics = ""

[module]
noProxy = 'none'
noVendor = ''
private = '*.*'
proxy = 'direct'
# replacements = ''
vendorClosest = false
workspace = 'off'

[module.hugoVersion]
extended = true
min = "0.65.0"

[markup.goldmark.renderer]
hardWraps = true
unsafe = true
# xHTML = true

[markup.highlight]
codeFences = true
lineNos = true
lineNumbersInTable = true
noClasses = false

[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2

[outputs]
home = ["HTML", "RSS", "SearchIndex"]
section = ["HTML", "RSS", "SearchIndex"]
taxonomy = ["HTML", "RSS", "SearchIndex"]

[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "index"
isPlainText = true
notAlternative = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
