# The URL of your site.
baseURL = "http://example.org"
# Title of your site
title = "Hugo Theme Everest Demo Site"
# Name of Zzo theme folder in `themes/`.
theme = "Everest"

languageCode = "en-us"
# Default language to use (if you setup multilingual)
defaultContentLanguage = "en"
# baseURL/en/, baseURL/zh/ ...
defaultContentLanguageInSubdir = true
# Set `true` for Chinese/Japanese/Korean languages.
hasCJKLanguage = true

# The length of a post description on a list page.
summaryLength = 70
# if true, we can use future date for talks page
buildFuture = true

# copyright symbol: $copy; current year: {year}
copyright = "&copy;{year}, All Rights Reserved"
timeout = "300s"
enableEmoji = true
# Number of items per page in paginated lists.
paginate = 10
rssLimit = 100

# When true, the modified date will appear on a summary and single page.
# Since GitHub info needs to be fetched, this feature will slow down to build depending on a page number you have
enableGitInfo = false
# googleAnalytics = ""

[module]
noProxy = 'none'
noVendor = ''
private = '*.*'
proxy = 'direct'
# replacements = ''
vendorClosest = false
workspace = 'off'

[module.hugoVersion]
extended = true
min = "0.65.0"

[markup.goldmark.renderer]
hardWraps = true
unsafe = true

[markup.highlight]
codeFences = true
lineNos = true
lineNumbersInTable = true
noClasses = false

[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2

[outputs]
home = ["HTML", "RSS", "SearchIndex"]
section = ["HTML", "RSS", "SearchIndex"]
taxonomy = ["HTML", "RSS", "SearchIndex"]

[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "index"
isPlainText = true
notAlternative = true

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
