# logo
logoText = "Everest"
logoType = "short"   # long, short

description = "The demo site for the Everest theme in Hugo."

# custom style
custom_css = []
custom_js = []

# site icon
# https://www.favicon-generator.org/
useFaviconGenerator = true
meta_image = ""

# theme style
themecolor = "solarized"
themeOptions = ["light", "solarized", "kimbie", "dark", "hacker"]

# not show in home page
notAllowedTypesInHome = [
  "contact",
  "talks",
  "about",
  "showcase",
  "publication",
  "presentation",
  "resume",
  "gallery",
]

# not show in sidebar of home page
notAllowedTypesInHomeSidebar = [
  "about",
  "archive",
  "showcase",
  "publication",
  "presentation",
  "resume",
  "gallery",
]

# not show in archive page
notAllowedTypesInArchive = []

# not show in rss
notAllowedTypesInHomeFeed = [
  "about",
  "archive",
  "contact",
  "talks",
  "showcase",
  "publication",
  "presentation",
  "resume",
  "gallery",
]

# site width
viewportSize = "wide" # widest, wider, wide, normal, narrow

enableUiAnimation = true

hideSingleContentsWhenJSDisabled = false

# pin posts
enablePinnedPosts = true

# Minimum items to show in tag cloud
minItemsToShowInTagCloud = 1

# top nav bar
enableAppbarSearchIcon = false
enableAppbarLangIcon = true
enableThemeChange = true

# home page header
homeHeaderType = "slide"         # text, img, slide, typewriter
hideHomeHeaderWhenMobile = false

# menu
showMobileMenuTerms = ["tags", "categories", "series"]

##########
# search #
##########
enableSearch = true
enableSearchHighlight = true
searchResultPosition = "main" # side, main
# include content to search index
searchContent = true
# fuse option
searchDistance = 100
searchThreshold = 0.4 # 0.0: exact match, 1.0: any match

########
# body #
########
enableBreadcrumb = true        # top relative path
summaryShape = "compact"       # card, classic, compact
archiveGroupByDate = "2006-01" # "2006-01": group by month, "2006": group by year
archivePaginate = 10
paginateWindow = 1
talksPaginate = 5
talksGroupByDate = "2006-01"
pubPaginate = 20
# icons
writtenTimeIcon = "📅"
modifiedTimeIcon = "📝"
readingTimeIcon = "⏳"
authorIcon = "✒️"
pagePvIcon = "👀"
pinIcon = "📌"
tagIcon = "🏷️"
publicationIcon = "📚"
typeIcon = "🎯"

##########
# whoami #
##########
myname = "Backtraxe"
email = "backtraxe$gmail.com"
whoami = ""
bioImageUrl = ""
useGravatar = false
location = ""
organization = ""
link = "https://github.com/backtraxe"

###########
# sidebar #
###########
enableSidebar = true
sidebarPosition = "right"
itemsPerCategory = 5
# profile
enableBio = true
enableBioImage = true
# other type
enableSidebarCategories = true
enableSidebarSeries = true
enableSidebarTags = true
# type: posts
enableHomeSidebarTitles = true   # display posts in the sidebar on the home page
enableListSidebarTitles = false  # display posts in the sidebar on the posts page
enableSidebarPostsByOrder = true
# toc
enableToc = true
hideToc = false
tocFolding = true
tocPosition = "inner"          # inner, outer
enableTocSwitch = true
tocLevels = ["h2", "h3", "h4"] # h1 - h6

######################
# blog share options #
######################
# facebook, twitter, reddit, linkedin, tumblr, line
# pocket, feedly, hatena, pinterest, delicious, google
# weibo, douban
# [[share]]
# name = ""
# username = ""

##########
# footer #
##########
enableGoToTop = true
enableWhoami = false
showPoweredBy = true
showFeedLinks = false
showSocialLinks = false
enableLangChange = false

################
# footer links #
################
[[footerLinks]]
name = ""
link = ""

[[footerLinks]]
name = ""
link = ""

###########
# service #
###########
googleTagManager = ""  # GTM-XXXXXX
baiduAnalytics = ""
enableBusuanzi = false
busuanziSiteUV = false
busuanziSitePV = false
busuanziPagePV = false

#######
# rss #
#######
updatePeriod = ""    # hourly, daily, weekly, monthly, yearly
updateFrequency = ""
fullContents = false

###########
# comment #
###########
enableComment = true
disqus_shortname = ""
commento = false

[telegram]
enable = false
siteId = ""
dataLimit = 5

# Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
[gitment]
owner = ""        # Your GitHub ID
repo = ""         # The repo to store comments
clientId = ""     # Your client ID
clientSecret = "" # Your client secret

# https://utteranc.es/
[utterances]
owner = "" # Your GitHub ID
repo = ""  # The repo to store comments

# Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
[gitalk]
owner = ""        # Your GitHub ID
repo = ""         # The repo to store comments
clientId = ""     # Your client ID
clientSecret = "" # Your client secret

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[valine]
enable = false
appId = '你的appId'
appKey = '你的appKey'
notify = false           # mail notifier , https://github.com/xCss/Valine/wiki
verify = false           # Verification code
avatar = 'mm'
placeholder = '说点什么吧...'
visitor = false

# 畅言
[changyan]
changyanAppid = ""  # Changyan app id
changyanAppkey = "" # Changyan app key

# 来必力
[livere]
livereUID = "" # LiveRe UID

# Isso: https://posativ.org/isso/
[isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

###############################
# sidebar whoami social icons #
###############################
[socialOptions]
email = ""
phone = ""
facebook = ""
twitter = ""
github = ""
stack-overflow = ""
instagram = ""
google-plus = ""
youtube = ""
medium = ""
tumblr = ""
linkedin = ""
pinterest = ""
stack-exchange = ""
telegram = ""
steam = ""
weibo = ""
douban = ""
csdn = ""
gitlab = ""
mastodon = ""
jianshu = ""
zhihu = ""
signal = ""
whatsapp = ""
matrix = ""
xmpp = ""
dev-to = ""
gitea = ""
google-scholar = ""

############
# donation #
############
[donationOptions]
enable = false
alipay = ""
wechat = ""
paypal = ""
patreon = ""
